MKDIR original
COPY *.mp original
START /WAIT "R_SAM" "C:\Program Files\RAMASGIS\Metapop.exe" "SandLizard_1_modified_0001.mp" /RUN=YES /TEX
RENAME Abund.txt Abund_0001.txt
RENAME FinalStageN.txt FinalStageN_0001.txt
RENAME Harvest.txt Harvest_0001.txt
RENAME HarvestRisk.txt HarvestRisk_0001.txt
RENAME IntExpRisk.txt IntExpRisk_0001.txt
RENAME IntExtRisk.txt IntExtRisk_0001.txt
RENAME IntPerDec.txt IntPerDec_0001.txt
RENAME LocalOcc.txt LocalOcc_0001.txt
RENAME LocExtDur.txt LocExtDur_0001.txt
RENAME MetapopOcc.txt MetapopOcc_0001.txt
RENAME QuasiExp.txt QuasiExp_0001.txt
RENAME QuasiExt.txt QuasiExt_0001.txt
RENAME TerExpRisk.txt TerExpRisk_0001.txt
RENAME TerExtRisk.txt TerExtRisk_0001.txt
RENAME TerPerDec.txt TerPerDec_0001.txt
START /WAIT "R_SAM" "C:\Program Files\RAMASGIS\Metapop.exe" "SandLizard_1_modified_0002.mp" /RUN=YES /TEX
RENAME Abund.txt Abund_0002.txt
RENAME FinalStageN.txt FinalStageN_0002.txt
RENAME Harvest.txt Harvest_0002.txt
RENAME HarvestRisk.txt HarvestRisk_0002.txt
RENAME IntExpRisk.txt IntExpRisk_0002.txt
RENAME IntExtRisk.txt IntExtRisk_0002.txt
RENAME IntPerDec.txt IntPerDec_0002.txt
RENAME LocalOcc.txt LocalOcc_0002.txt
RENAME LocExtDur.txt LocExtDur_0002.txt
RENAME MetapopOcc.txt MetapopOcc_0002.txt
RENAME QuasiExp.txt QuasiExp_0002.txt
RENAME QuasiExt.txt QuasiExt_0002.txt
RENAME TerExpRisk.txt TerExpRisk_0002.txt
RENAME TerExtRisk.txt TerExtRisk_0002.txt
RENAME TerPerDec.txt TerPerDec_0002.txt
START /WAIT "R_SAM" "C:\Program Files\RAMASGIS\Metapop.exe" "SandLizard_1_modified_0003.mp" /RUN=YES /TEX
RENAME Abund.txt Abund_0003.txt
RENAME FinalStageN.txt FinalStageN_0003.txt
RENAME Harvest.txt Harvest_0003.txt
RENAME HarvestRisk.txt HarvestRisk_0003.txt
RENAME IntExpRisk.txt IntExpRisk_0003.txt
RENAME IntExtRisk.txt IntExtRisk_0003.txt
RENAME IntPerDec.txt IntPerDec_0003.txt
RENAME LocalOcc.txt LocalOcc_0003.txt
RENAME LocExtDur.txt LocExtDur_0003.txt
RENAME MetapopOcc.txt MetapopOcc_0003.txt
RENAME QuasiExp.txt QuasiExp_0003.txt
RENAME QuasiExt.txt QuasiExt_0003.txt
RENAME TerExpRisk.txt TerExpRisk_0003.txt
RENAME TerExtRisk.txt TerExtRisk_0003.txt
RENAME TerPerDec.txt TerPerDec_0003.txt
