MKDIR original
COPY *.mp original
START /WAIT "R_SAM" "C:\Program Files\RAMASGIS\Metapop.exe" "SandLizard_1_modified_0001.mp" /RUN=YES /TEX
RENAME Abund.txt Abund_0001.txt
RENAME FinalStageN.txt FinalStageN_0001.txt
RENAME Harvest.txt Harvest_0001.txt
RENAME HarvestRisk.txt HarvestRisk_0001.txt
RENAME IntExpRisk.txt IntExpRisk_0001.txt
RENAME IntExtRisk.txt IntExtRisk_0001.txt
RENAME IntPerDec.txt IntPerDec_0001.txt
RENAME LocalOcc.txt LocalOcc_0001.txt
RENAME LocExtDur.txt LocExtDur_0001.txt
RENAME MetapopOcc.txt MetapopOcc_0001.txt
RENAME QuasiExp.txt QuasiExp_0001.txt
RENAME QuasiExt.txt QuasiExt_0001.txt
RENAME TerExpRisk.txt TerExpRisk_0001.txt
RENAME TerExtRisk.txt TerExtRisk_0001.txt
RENAME TerPerDec.txt TerPerDec_0001.txt
START /WAIT "R_SAM" "C:\Program Files\RAMASGIS\Metapop.exe" "SandLizard_1_modified_0002.mp" /RUN=YES /TEX
RENAME Abund.txt Abund_0002.txt
RENAME FinalStageN.txt FinalStageN_0002.txt
RENAME Harvest.txt Harvest_0002.txt
RENAME HarvestRisk.txt HarvestRisk_0002.txt
RENAME IntExpRisk.txt IntExpRisk_0002.txt
RENAME IntExtRisk.txt IntExtRisk_0002.txt
RENAME IntPerDec.txt IntPerDec_0002.txt
RENAME LocalOcc.txt LocalOcc_0002.txt
RENAME LocExtDur.txt LocExtDur_0002.txt
RENAME MetapopOcc.txt MetapopOcc_0002.txt
RENAME QuasiExp.txt QuasiExp_0002.txt
RENAME QuasiExt.txt QuasiExt_0002.txt
RENAME TerExpRisk.txt TerExpRisk_0002.txt
RENAME TerExtRisk.txt TerExtRisk_0002.txt
RENAME TerPerDec.txt TerPerDec_0002.txt
START /WAIT "R_SAM" "C:\Program Files\RAMASGIS\Metapop.exe" "SandLizard_1_modified_0003.mp" /RUN=YES /TEX
RENAME Abund.txt Abund_0003.txt
RENAME FinalStageN.txt FinalStageN_0003.txt
RENAME Harvest.txt Harvest_0003.txt
RENAME HarvestRisk.txt HarvestRisk_0003.txt
RENAME IntExpRisk.txt IntExpRisk_0003.txt
RENAME IntExtRisk.txt IntExtRisk_0003.txt
RENAME IntPerDec.txt IntPerDec_0003.txt
RENAME LocalOcc.txt LocalOcc_0003.txt
RENAME LocExtDur.txt LocExtDur_0003.txt
RENAME MetapopOcc.txt MetapopOcc_0003.txt
RENAME QuasiExp.txt QuasiExp_0003.txt
RENAME QuasiExt.txt QuasiExt_0003.txt
RENAME TerExpRisk.txt TerExpRisk_0003.txt
RENAME TerExtRisk.txt TerExtRisk_0003.txt
RENAME TerPerDec.txt TerPerDec_0003.txt
START /WAIT "R_SAM" "C:\Program Files\RAMASGIS\Metapop.exe" "SandLizard_1_modified_0004.mp" /RUN=YES /TEX
RENAME Abund.txt Abund_0004.txt
RENAME FinalStageN.txt FinalStageN_0004.txt
RENAME Harvest.txt Harvest_0004.txt
RENAME HarvestRisk.txt HarvestRisk_0004.txt
RENAME IntExpRisk.txt IntExpRisk_0004.txt
RENAME IntExtRisk.txt IntExtRisk_0004.txt
RENAME IntPerDec.txt IntPerDec_0004.txt
RENAME LocalOcc.txt LocalOcc_0004.txt
RENAME LocExtDur.txt LocExtDur_0004.txt
RENAME MetapopOcc.txt MetapopOcc_0004.txt
RENAME QuasiExp.txt QuasiExp_0004.txt
RENAME QuasiExt.txt QuasiExt_0004.txt
RENAME TerExpRisk.txt TerExpRisk_0004.txt
RENAME TerExtRisk.txt TerExtRisk_0004.txt
RENAME TerPerDec.txt TerPerDec_0004.txt
START /WAIT "R_SAM" "C:\Program Files\RAMASGIS\Metapop.exe" "SandLizard_1_modified_0005.mp" /RUN=YES /TEX
RENAME Abund.txt Abund_0005.txt
RENAME FinalStageN.txt FinalStageN_0005.txt
RENAME Harvest.txt Harvest_0005.txt
RENAME HarvestRisk.txt HarvestRisk_0005.txt
RENAME IntExpRisk.txt IntExpRisk_0005.txt
RENAME IntExtRisk.txt IntExtRisk_0005.txt
RENAME IntPerDec.txt IntPerDec_0005.txt
RENAME LocalOcc.txt LocalOcc_0005.txt
RENAME LocExtDur.txt LocExtDur_0005.txt
RENAME MetapopOcc.txt MetapopOcc_0005.txt
RENAME QuasiExp.txt QuasiExp_0005.txt
RENAME QuasiExt.txt QuasiExt_0005.txt
RENAME TerExpRisk.txt TerExpRisk_0005.txt
RENAME TerExtRisk.txt TerExtRisk_0005.txt
RENAME TerPerDec.txt TerPerDec_0005.txt
START /WAIT "R_SAM" "C:\Program Files\RAMASGIS\Metapop.exe" "SandLizard_1_modified_0006.mp" /RUN=YES /TEX
RENAME Abund.txt Abund_0006.txt
RENAME FinalStageN.txt FinalStageN_0006.txt
RENAME Harvest.txt Harvest_0006.txt
RENAME HarvestRisk.txt HarvestRisk_0006.txt
RENAME IntExpRisk.txt IntExpRisk_0006.txt
RENAME IntExtRisk.txt IntExtRisk_0006.txt
RENAME IntPerDec.txt IntPerDec_0006.txt
RENAME LocalOcc.txt LocalOcc_0006.txt
RENAME LocExtDur.txt LocExtDur_0006.txt
RENAME MetapopOcc.txt MetapopOcc_0006.txt
RENAME QuasiExp.txt QuasiExp_0006.txt
RENAME QuasiExt.txt QuasiExt_0006.txt
RENAME TerExpRisk.txt TerExpRisk_0006.txt
RENAME TerExtRisk.txt TerExtRisk_0006.txt
RENAME TerPerDec.txt TerPerDec_0006.txt
START /WAIT "R_SAM" "C:\Program Files\RAMASGIS\Metapop.exe" "SandLizard_1_modified_0007.mp" /RUN=YES /TEX
RENAME Abund.txt Abund_0007.txt
RENAME FinalStageN.txt FinalStageN_0007.txt
RENAME Harvest.txt Harvest_0007.txt
RENAME HarvestRisk.txt HarvestRisk_0007.txt
RENAME IntExpRisk.txt IntExpRisk_0007.txt
RENAME IntExtRisk.txt IntExtRisk_0007.txt
RENAME IntPerDec.txt IntPerDec_0007.txt
RENAME LocalOcc.txt LocalOcc_0007.txt
RENAME LocExtDur.txt LocExtDur_0007.txt
RENAME MetapopOcc.txt MetapopOcc_0007.txt
RENAME QuasiExp.txt QuasiExp_0007.txt
RENAME QuasiExt.txt QuasiExt_0007.txt
RENAME TerExpRisk.txt TerExpRisk_0007.txt
RENAME TerExtRisk.txt TerExtRisk_0007.txt
RENAME TerPerDec.txt TerPerDec_0007.txt
START /WAIT "R_SAM" "C:\Program Files\RAMASGIS\Metapop.exe" "SandLizard_1_modified_0008.mp" /RUN=YES /TEX
RENAME Abund.txt Abund_0008.txt
RENAME FinalStageN.txt FinalStageN_0008.txt
RENAME Harvest.txt Harvest_0008.txt
RENAME HarvestRisk.txt HarvestRisk_0008.txt
RENAME IntExpRisk.txt IntExpRisk_0008.txt
RENAME IntExtRisk.txt IntExtRisk_0008.txt
RENAME IntPerDec.txt IntPerDec_0008.txt
RENAME LocalOcc.txt LocalOcc_0008.txt
RENAME LocExtDur.txt LocExtDur_0008.txt
RENAME MetapopOcc.txt MetapopOcc_0008.txt
RENAME QuasiExp.txt QuasiExp_0008.txt
RENAME QuasiExt.txt QuasiExt_0008.txt
RENAME TerExpRisk.txt TerExpRisk_0008.txt
RENAME TerExtRisk.txt TerExtRisk_0008.txt
RENAME TerPerDec.txt TerPerDec_0008.txt
START /WAIT "R_SAM" "C:\Program Files\RAMASGIS\Metapop.exe" "SandLizard_1_modified_0009.mp" /RUN=YES /TEX
RENAME Abund.txt Abund_0009.txt
RENAME FinalStageN.txt FinalStageN_0009.txt
RENAME Harvest.txt Harvest_0009.txt
RENAME HarvestRisk.txt HarvestRisk_0009.txt
RENAME IntExpRisk.txt IntExpRisk_0009.txt
RENAME IntExtRisk.txt IntExtRisk_0009.txt
RENAME IntPerDec.txt IntPerDec_0009.txt
RENAME LocalOcc.txt LocalOcc_0009.txt
RENAME LocExtDur.txt LocExtDur_0009.txt
RENAME MetapopOcc.txt MetapopOcc_0009.txt
RENAME QuasiExp.txt QuasiExp_0009.txt
RENAME QuasiExt.txt QuasiExt_0009.txt
RENAME TerExpRisk.txt TerExpRisk_0009.txt
RENAME TerExtRisk.txt TerExtRisk_0009.txt
RENAME TerPerDec.txt TerPerDec_0009.txt
START /WAIT "R_SAM" "C:\Program Files\RAMASGIS\Metapop.exe" "SandLizard_1_modified_0010.mp" /RUN=YES /TEX
RENAME Abund.txt Abund_0010.txt
RENAME FinalStageN.txt FinalStageN_0010.txt
RENAME Harvest.txt Harvest_0010.txt
RENAME HarvestRisk.txt HarvestRisk_0010.txt
RENAME IntExpRisk.txt IntExpRisk_0010.txt
RENAME IntExtRisk.txt IntExtRisk_0010.txt
RENAME IntPerDec.txt IntPerDec_0010.txt
RENAME LocalOcc.txt LocalOcc_0010.txt
RENAME LocExtDur.txt LocExtDur_0010.txt
RENAME MetapopOcc.txt MetapopOcc_0010.txt
RENAME QuasiExp.txt QuasiExp_0010.txt
RENAME QuasiExt.txt QuasiExt_0010.txt
RENAME TerExpRisk.txt TerExpRisk_0010.txt
RENAME TerExtRisk.txt TerExtRisk_0010.txt
RENAME TerPerDec.txt TerPerDec_0010.txt
